<?php declare(strict_types=1);use App\Support\View;$ok=static fn(bool$value):string=>$value?'text-bg-success':'text-bg-danger';?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-secondary mb-1">Administration</p><h1>System diagnostics</h1><p class="text-secondary">Read-only staging checks. Credentials and environment-file contents are never displayed.</p></div></div>
<div class="row g-3 mb-4">
<?php foreach([['PHP version',$phpVersion],['Application version',$applicationVersion],['Environment',$environment],['Application URL',rtrim($baseUrl,'/').($basePath===''?'':'/'.trim($basePath,'/'))]]as[$label,$value]):?><div class="col-md-6"><div class="card card-body h-100"><strong><?= View::escape($label) ?></strong><span><?= View::escape($value) ?></span></div></div><?php endforeach;?>
</div>
<section class="card card-body mb-4"><h2 class="h4">Database</h2><p><span class="badge <?= $ok($database['connected']) ?>"><?= View::escape($database['message']) ?></span></p>
<?php if($database['connected']):?><dl class="row mb-0"><dt class="col-sm-4">Users</dt><dd class="col-sm-8"><?= $counts['users'] ?></dd><dt class="col-sm-4">People</dt><dd class="col-sm-8"><?= $counts['people'] ?></dd><dt class="col-sm-4">Users without linked Person</dt><dd class="col-sm-8"><span class="badge <?= $ok($counts['unlinkedUsers']===0) ?>"><?= $counts['unlinkedUsers'] ?></span></dd></dl><?php endif;?></section>
<section class="card card-body mb-4"><h2 class="h4">Migrations</h2><p><span class="badge <?= $ok($migrations['missing']===[]) ?>"><?= $migrations['missing']===[]?'Current':'Incomplete' ?></span></p><p class="mb-1">Applied: <?= View::escape(implode(', ',$migrations['applied'])?:'None') ?></p><p class="mb-0">Missing: <?= View::escape(implode(', ',$migrations['missing'])?:'None') ?></p></section>
<section class="card card-body"><h2 class="h4">Writable directories</h2><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Purpose</th><th>Path</th><th>Status</th></tr></thead><tbody><?php foreach($writable as$item):?><tr><td><?= View::escape($item['label']) ?></td><td><code><?= View::escape($item['path']) ?></code></td><td><span class="badge <?= $ok($item['writable']) ?>"><?= $item['writable']?'Writable':'Not writable' ?></span></td></tr><?php endforeach;?></tbody></table></div></section>
