<?php declare(strict_types=1);use App\Support\View;?>
<header class="page-heading"><div><p class="eyebrow">Account</p><h1>My Profile</h1><p class="text-secondary mb-0">Manage your sign-in details and review your linked Person record.</p></div></header>
<div class="row g-4">
<section class="col-lg-6"><div class="card card-body h-100"><h2 class="h4">Account</h2><dl class="row"><dt class="col-sm-4">Username</dt><dd class="col-sm-8"><?= View::escape($user->username) ?></dd><dt class="col-sm-4">Role</dt><dd class="col-sm-8"><?= View::escape($user->roleLabel()) ?></dd></dl>
<form method="post" action="<?= View::escape($urls->to('/profile/email')) ?>" novalidate><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><label class="form-label" for="profile-email">Email</label><input class="form-control<?= isset($emailErrors['email'])?' is-invalid':'' ?>" id="profile-email" name="email" type="email" value="<?= View::escape($emailValues['email']??$user->email) ?>" required><?php if(isset($emailErrors['email'])):?><div class="invalid-feedback"><?= View::escape($emailErrors['email']) ?></div><?php endif;?><button class="btn btn-primary mt-3">Save email</button></form></div></section>
<section class="col-lg-6"><div class="card card-body h-100"><h2 class="h4">Change password</h2><form method="post" action="<?= View::escape($urls->to('/profile/password')) ?>" novalidate><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><?php foreach(['current_password'=>'Current password','new_password'=>'New password','new_password_confirmation'=>'Confirm new password']as$field=>$label):?><div class="mb-3"><label class="form-label" for="<?= $field ?>"><?= $label ?></label><input class="form-control<?= isset($passwordErrors[$field])?' is-invalid':'' ?>" id="<?= $field ?>" name="<?= $field ?>" type="password" autocomplete="<?= $field==='current_password'?'current-password':'new-password' ?>" required><?php if(isset($passwordErrors[$field])):?><div class="invalid-feedback"><?= View::escape($passwordErrors[$field]) ?></div><?php endif;?></div><?php endforeach;?><button class="btn btn-primary">Change password</button></form></div></section>
<section class="col-12"><div class="card card-body"><h2 class="h4">Personal information</h2><?php if($person===null):?><div class="alert alert-warning mb-0">Your account is not linked to a Person record. An administrator can manage this link from Users.</div><?php else:?><dl class="row mb-0"><dt class="col-sm-4 col-lg-3">Name</dt><dd class="col-sm-8 col-lg-9"><?= View::escape($person->firstName) ?></dd><dt class="col-sm-4 col-lg-3">Surname</dt><dd class="col-sm-8 col-lg-9"><?= View::escape($person->lastName) ?></dd><dt class="col-sm-4 col-lg-3">Position</dt><dd class="col-sm-8 col-lg-9"><?= View::escape($person->positionLabel()) ?></dd><dt class="col-sm-4 col-lg-3">Department / affiliation</dt><dd class="col-sm-8 col-lg-9"><?= View::escape($person->affiliation??'—') ?></dd><dt class="col-sm-4 col-lg-3">Annual capacity</dt><dd class="col-sm-8 col-lg-9"><?= View::escape($person->annualCapacityHours) ?> h/year</dd></dl><?php endif;?></div></section>
<section class="col-12"><div class="card card-body text-secondary"><h2 class="h5 text-body">Preferences</h2><p class="mb-0">Personal preferences will be available here in a future release.</p></div></section>
</div>
