<?php declare(strict_types=1);use App\Support\View;$months=[];for($m=1;$m<=12;$m++)$months[$m]=(new DateTimeImmutable("2026-$m-01"))->format('M');?>
<header class="page-heading"><div><p class="eyebrow">Capacity</p><h1>All-People capacity</h1><p class="text-secondary mb-0">Annual availability and allocations for People in your authorized scope.</p></div>
<div class="year-navigation" aria-label="Capacity year"><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/capacity',['year'=>$page->year-1])) ?>">← <?= $page->year-1 ?></a><form method="get" action="<?= View::escape($urls->to('/capacity')) ?>"><label class="visually-hidden" for="capacity-year">Year</label><input class="form-control" id="capacity-year" name="year" value="<?= $page->year ?>" inputmode="numeric"><button class="btn btn-outline-primary">Go</button></form><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/capacity',['year'=>$page->year+1])) ?>"><?= $page->year+1 ?> →</a></div></header>
<?php if($page->people===[]):?><div class="empty-state"><h2>No people available</h2><p>No people are available in your capacity scope.</p></div><?php else:?>
<?php $loadChart=$page->people;usort($loadChart,static fn(array$a,array$b):int=>($a['utilizationPercent']??PHP_INT_MAX)<=>($b['utilizationPercent']??PHP_INT_MAX));?>
<section class="capacity-load-chart" aria-labelledby="capacity-load-title"><div class="capacity-load-heading"><div><h2 id="capacity-load-title">Annual workload at a glance</h2><p>Sorted from the most available person. A shorter bar means more capacity is still available.</p></div><span class="capacity-load-legend"><i aria-hidden="true"></i> Allocated / capacity</span></div>
<div class="capacity-load-list"><?php foreach($loadChart as$entry):$person=$entry['person'];$percent=$entry['utilizationPercent'];$barWidth=$percent===null?0:min(100,max(0,$percent));$over=$percent!==null&&$percent>100;?>
<div class="capacity-load-row"><a class="capacity-load-person" href="#capacity-person-<?= $person->id ?>"><?= View::escape($person->fullName()) ?></a><div class="capacity-load-meter<?= $over?' is-over':'' ?>" role="img" aria-label="<?= View::escape($person->fullName().': '.$entry['annualAllocated'].' of '.$entry['annualCapacity'].' hours allocated'.($percent===null?'':', '.$percent.' percent')) ?>"><span style="--capacity-load:<?= $barWidth ?>%"></span></div><div class="capacity-load-value"><strong><?= $percent===null?'—':$percent.'%' ?></strong><small><?= $over?View::escape(ltrim($entry['annualRemaining'],'-')).' h over':View::escape($entry['annualRemaining']).' h available' ?></small></div></div>
<?php endforeach;?></div></section>
<div class="capacity-overview-tools"><div class="capacity-overview-search"><label for="capacity-person-search">Search People</label><input class="form-control" id="capacity-person-search" type="search" data-capacity-search placeholder="Name, email, or username"></div><div class="capacity-overview-actions"><button class="btn btn-outline-secondary" type="button" data-capacity-expand-all>Expand all</button><button class="btn btn-outline-secondary" type="button" data-capacity-collapse-all>Collapse all</button></div></div>
<div class="capacity-overview" data-capacity-overview data-default-expanded="<?= $page->defaultExpanded?'1':'0' ?>">
<?php foreach($page->people as$entry):$person=$entry['person'];$id='capacity-person-'.$person->id;$search=strtolower(implode(' ',[$person->fullName(),$person->institutionalEmail,$person->linkedUsername]));?>
<section class="capacity-person" data-capacity-person data-person-search="<?= View::escape($search) ?>"><h2><button type="button" class="capacity-person-toggle" aria-expanded="true" aria-controls="<?= $id ?>" data-capacity-toggle><span class="capacity-chevron" aria-hidden="true">⌄</span><span><?= View::escape($person->fullName()) ?></span><small><?= $person->linkedUsername!==null?'Linked user':'Unlinked' ?> · <?= $person->isActive?'Active':'Inactive' ?> · <?= $entry['overrideCount'] ?> override<?= $entry['overrideCount']===1?'':'s' ?></small><strong><?= View::escape($entry['annualCapacity']) ?> h annual capacity</strong></button></h2>
<div id="<?= $id ?>" class="capacity-person-panel" data-capacity-panel>
<div class="table-responsive capacity-overview-table"><table class="table table-sm table-bordered align-middle mb-0"><thead><tr><th scope="col">Measure</th><?php foreach($months as$name):?><th scope="col"><?= $name ?></th><?php endforeach;?><th scope="col">Annual</th></tr></thead><tbody>
<tr><th scope="row">Capacity</th><?php foreach($entry['months']as$m):?><td class="<?= $m->capacity->source==='override'?'capacity-override':'' ?>"><?= View::escape($m->capacity->effectiveHours) ?><small><?= View::escape($m->capacity->source) ?></small></td><?php endforeach;?><td><strong><?= View::escape($entry['annualCapacity']) ?></strong></td></tr>
<tr><th scope="row">Allocated</th><?php foreach($entry['months']as$m):?><td class="<?= $m->allocatedStatus($decimals)==='overallocated'?'table-warning':'' ?>"><?= View::escape($m->allocatedHours()) ?></td><?php endforeach;?><td><strong><?= View::escape($entry['annualAllocated']) ?></strong></td></tr>
<tr><th scope="row">Remaining</th><?php foreach($entry['months']as$m):?><td><?= View::escape($m->remaining($decimals)) ?></td><?php endforeach;?><td><strong><?= View::escape($entry['annualRemaining']) ?></strong></td></tr>
</tbody></table></div><div class="capacity-person-actions"><?php if($page->canEdit):?><a class="btn btn-sm btn-outline-primary" href="<?= View::escape($urls->to('/people/'.$person->id.'/capacity',['year'=>$page->year])) ?>">Edit capacity</a><?php endif;?></div></div></section>
<?php endforeach;?></div><?php endif;?>
