<?php
declare(strict_types=1);
use App\Support\View;
$edit=$mode==='edit';
$base='/projects/'.$project->id.'/participants';
$action=$edit?$base.'/'.$participant->id:$base;
?>
<div class="row justify-content-center"><div class="col-xl-9"><div class="d-flex justify-content-between mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->displayTitle()) ?></p><h1 class="h2"><?= View::escape($title) ?></h1></div><a href="<?= View::escape($urls->to($base)) ?>">Back to participants</a></div>
<div class="alert alert-info">Project period: <?= View::escape($project->period()) ?>. Participation and project-manager ownership are independent.</div>
<form class="card card-body shadow-sm" method="post" action="<?= View::escape($urls->to($action)) ?>" novalidate><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><div class="row g-3">
<?php if(!$edit):?><div class="col-12"><label class="form-label" for="person_id">Person</label><select class="form-select<?= isset($errors['person_id'])?' is-invalid':'' ?>" id="person_id" name="person_id" required><option value="">Select a person</option><?php foreach($peopleOptions as $option):?><option value="<?= $option->id ?>" data-active-from="<?= View::escape($option->activeFrom??'') ?>" data-active-to="<?= View::escape($option->activeTo??'') ?>" <?= ($values['person_id']??'')===(string)$option->id?'selected':'' ?>><?= View::escape($option->label()) ?></option><?php endforeach;?></select><?php if(isset($errors['person_id'])):?><div class="invalid-feedback"><?= View::escape($errors['person_id']) ?></div><?php endif;?><div class="form-text">Only people not already participating are listed. Inactive people may be selected and are clearly marked.</div></div>
<?php else:?><div class="col-12"><label class="form-label">Person</label><p class="form-control-plaintext"><?= View::escape($participant->personName()) ?> — <?= View::escape($participant->positionLabel()) ?><?= $participant->affiliation!==null?' — '.View::escape($participant->affiliation):'' ?></p><div class="form-text">To change the person, remove this participation and add a new one. Person association: <?= View::escape(($participant->personActiveFrom?->format('Y-m-d')??'Open').' — '.($participant->personActiveTo?->format('Y-m-d')??'Open')) ?>.</div></div><?php endif;?>
<div class="col-md-6"><label class="form-label" for="project_role">Project role</label><select class="form-select<?= isset($errors['project_role'])?' is-invalid':'' ?>" id="project_role" name="project_role"><?php foreach($roleLabels as $value=>$label):?><option value="<?= $value ?>" <?= ($values['project_role']??'')===$value?'selected':'' ?>><?= View::escape($label) ?></option><?php endforeach;?></select><?php if(isset($errors['project_role'])):?><div class="invalid-feedback"><?= View::escape($errors['project_role']) ?></div><?php endif;?></div>
<div class="col-md-3"><label class="form-label" for="participation_start">Participation start</label><input class="form-control<?= isset($errors['participation_start'])?' is-invalid':'' ?>" type="date" id="participation_start" name="participation_start" value="<?= View::escape($values['participation_start']??'') ?>"><?php if(isset($errors['participation_start'])):?><div class="invalid-feedback"><?= View::escape($errors['participation_start']) ?></div><?php endif;?></div>
<div class="col-md-3"><label class="form-label" for="participation_end">Participation end</label><input class="form-control<?= isset($errors['participation_end'])?' is-invalid':'' ?>" type="date" id="participation_end" name="participation_end" value="<?= View::escape($values['participation_end']??'') ?>"><?php if(isset($errors['participation_end'])):?><div class="invalid-feedback"><?= View::escape($errors['participation_end']) ?></div><?php endif;?></div>
<div class="col-12"><div class="form-check"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" <?= ($values['is_active']??'0')==='1'?'checked':'' ?>><label class="form-check-label" for="is_active">Active participation</label></div><div class="form-text">This state is not derived from dates, project state, person state, or account state.</div></div>
<div class="col-12"><label class="form-label" for="notes">Internal notes</label><textarea class="form-control<?= isset($errors['notes'])?' is-invalid':'' ?>" id="notes" name="notes" maxlength="2000" rows="4"><?= View::escape($values['notes']??'') ?></textarea><?php if(isset($errors['notes'])):?><div class="invalid-feedback"><?= View::escape($errors['notes']) ?></div><?php endif;?><div class="form-text">Visible only to the administrator and the owning project manager.</div></div>
</div><button class="btn btn-primary mt-4 align-self-start" type="submit"><?= $edit?'Save changes':'Add participant' ?></button></form></div></div>
