<?php
declare(strict_types=1);
use App\Support\View;
$allocationCount=$allocationCount??0;$recentAllocations=$recentAllocations??[];$converter=$converter??new App\Support\PersonMonthConverter();
$allocationTotals=$allocationTotals??new App\Models\HourTotals('0.00','0.00',0);$unifiedAllocationTotals=$unifiedAllocationTotals??$allocationTotals;$divergentAllocationCount=$divergentAllocationCount??0;$hasAllocations=$hasAllocations??false;$responsibleWorkPackages=$responsibleWorkPackages??[];
$base='/projects/'.$project->id.'/participants/'.$participant->id;
?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->displayTitle()) ?></p><h1><?= View::escape($participant->personName()) ?></h1></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants')) ?>">All participants</a><?php if($canManage):?><a class="btn btn-primary" href="<?= View::escape($urls->to($base.'/edit')) ?>">Edit</a><?php endif;?></div></div>
<?php if(!$participant->personIsActive||$participant->linkedUserIsActive===false||$project->status!=='active'||!$participant->isActive):?><div class="alert alert-warning">States are independent: project <?= View::escape(strtolower($project->statusLabel())) ?>; participation <?= View::escape(strtolower($participant->activeLabel())) ?>; person <?= $participant->personIsActive?'active':'inactive' ?><?= $participant->linkedUserIsActive===false?'; linked account inactive':'' ?>.</div><?php endif;?>
<div class="card card-body shadow-sm"><dl class="row mb-0">
<?php foreach(['Project'=>$participant->projectName(),'Person'=>$participant->personName(),'Professional position'=>$participant->positionLabel(),'Affiliation'=>$participant->affiliation,'Institutional email'=>$participant->institutionalEmail,'Linked username'=>$participant->linkedUsername,'Project role'=>$participant->roleLabel(),'Participation period'=>$participant->period(),'Participation state'=>$participant->activeLabel()] as $label=>$value):?><dt class="col-md-3"><?= View::escape($label) ?></dt><dd class="col-md-9"><?= View::escape($value??'—') ?></dd><?php endforeach;?>
<?php if($canViewNotes):?><dt class="col-md-3">Internal notes</dt><dd class="col-md-9"><?= nl2br(View::escape($participant->notes??'—')) ?></dd><?php endif;?>
<dt class="col-md-3">Created</dt><dd class="col-md-9"><?= View::escape($participant->createdAt->format('Y-m-d H:i')) ?></dd><dt class="col-md-3">Updated</dt><dd class="col-md-9"><?= View::escape($participant->updatedAt->format('Y-m-d H:i')) ?></dd>
</dl></div>
<section class="mt-5"><h2 class="h4">Responsible Work Packages</h2><?php if($responsibleWorkPackages===[]):?><div class="card card-body text-secondary">This participant is not responsible for a Work Package.</div><?php else:?><div class="table-responsive bg-white border rounded"><table class="table table-striped mb-0"><thead><tr><th>Project</th><th>Code</th><th>Title</th><th>Dates</th><th>State</th></tr></thead><tbody><?php foreach($responsibleWorkPackages as$wp):?><tr><td><?= View::escape($wp->projectAcronym) ?></td><td><a href="<?= View::escape($urls->to('/projects/'.$project->id.'/work-packages/'.$wp->id)) ?>"><?= View::escape($wp->code) ?></a></td><td><?= View::escape($wp->title) ?></td><td><?= View::escape($wp->period()) ?></td><td><?= $wp->isActive?'Active':'Inactive' ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="mt-5"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">Person-Hour Allocations</h2><p class="text-secondary mb-0"><?= $allocationTotals->allocationCount ?> allocation row<?= $allocationTotals->allocationCount===1?'':'s' ?> across <?= $allocationTotals->distinctMonthCount ?> distinct month<?= $allocationTotals->distinctMonthCount===1?'':'s' ?>; PM values use <?= View::escape($project->hoursPerPm) ?> hours/PM</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= View::escape($urls->to($base.'/allocations')) ?>">View all</a><?php if($canManage):?><a class="btn btn-primary" href="<?= View::escape($urls->to($base.'/allocations/create')) ?>">Add allocation</a><?php endif;?></div></div>
<?php if($divergentAllocationCount>0):?><div class="alert alert-warning"><?= $divergentAllocationCount ?> legacy inconsistent record<?= $divergentAllocationCount===1?' is':'s are' ?> excluded from unified totals.</div><?php endif;?><div class="row g-3 mb-3"><?php foreach(['Person-hours'=>$unifiedAllocationTotals->allocatedHours(),'Derived PM'=>$converter->convert($unifiedAllocationTotals->allocatedHours(),$project->hoursPerPm),'Allocation rows'=>(string)$unifiedAllocationTotals->allocationCount]as$label=>$value):?><div class="col-sm-6 col-lg"><div class="card card-body"><small class="text-secondary"><?= View::escape($label) ?></small><strong><?= View::escape($value) ?></strong></div></div><?php endforeach;?></div>
<?php if($recentAllocations!==[]):?><div class="table-responsive bg-white border rounded"><table class="table table-striped mb-0"><thead><tr><th>Month</th><th>Allocated h</th><th>Allocated PM</th></tr></thead><tbody><?php foreach($recentAllocations as$a):?><tr><td><a href="<?= View::escape($urls->to($base.'/allocations/'.$a->id)) ?>"><?= View::escape($a->monthLabel()) ?></a></td><td><?= View::escape($a->allocatedHours()??'—') ?></td><td><?= View::escape($a->allocatedPm($converter)??'—') ?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="card card-body text-secondary">No monthly allocations have been recorded.</div><?php endif;?><p class="form-text">Person-hours are stored; Person-Month values are derived from the project’s current conversion factor.</p></section>
<?php if($canManage):?><div class="d-flex gap-2 mt-4">
<form method="post" action="<?= View::escape($urls->to($base.'/'.($participant->isActive?'deactivate':'activate'))) ?>"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><button class="btn btn-outline-primary" type="submit"><?= $participant->isActive?'Deactivate':'Activate' ?></button></form>
<?php if(!$hasAllocations&&$responsibleWorkPackages===[]):?><a class="btn btn-outline-danger" href="<?= View::escape($urls->to($base.'/remove')) ?>">Remove participation</a><?php else:?><span class="text-secondary align-self-center"><?= $hasAllocations?'Historical allocations':'Work Package responsibility' ?> prevents removal; deactivate or clear responsibility instead.</span><?php endif;?>
</div><?php endif;?>
