<?php

declare(strict_types=1);

use App\Support\View;

$isEdit = $mode === 'edit';
$action = $isEdit ? '/admin/people/'.$person->id : '/admin/people';
?>
<div class="row justify-content-center"><div class="col-xl-9">
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h2 mb-0"><?= View::escape($title) ?></h1><a href="<?= View::escape($urls->to('/admin/people')) ?>">Back to people</a></div>
<form class="card card-body shadow-sm" method="post" action="<?= View::escape($urls->to($action)) ?>" novalidate>
<input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>">
<div class="row g-3">
    <div class="col-12"><label class="form-label" for="user_id">Linked application account</label><select class="form-select<?= isset($errors['user_id'])?' is-invalid':'' ?>" id="user_id" name="user_id"><option value="">No linked user</option><?php foreach ($userOptions as $option): ?><option value="<?= $option->id ?>" <?= ($values['user_id']??'')===(string)$option->id?'selected':'' ?>><?= View::escape($option->label()) ?></option><?php endforeach; ?></select><div class="form-text">Linking does not synchronize names, email, role, password, or active status.</div><?php if(isset($errors['user_id'])):?><div class="invalid-feedback"><?= View::escape($errors['user_id']) ?></div><?php endif;?></div>
    <?php foreach(['first_name'=>'First name','last_name'=>'Last name'] as $field=>$label): ?><div class="col-md-6"><label class="form-label" for="<?= $field ?>"><?= $label ?></label><input class="form-control<?= isset($errors[$field])?' is-invalid':'' ?>" id="<?= $field ?>" name="<?= $field ?>" maxlength="100" value="<?= View::escape($values[$field]??'') ?>" required><?php if(isset($errors[$field])):?><div class="invalid-feedback"><?= View::escape($errors[$field]) ?></div><?php endif;?></div><?php endforeach; ?>
    <div class="col-md-6"><label class="form-label" for="institutional_email">Institutional email</label><input class="form-control<?= isset($errors['institutional_email'])?' is-invalid':'' ?>" id="institutional_email" name="institutional_email" type="email" maxlength="255" value="<?= View::escape($values['institutional_email']??'') ?>"><?php if(isset($errors['institutional_email'])):?><div class="invalid-feedback"><?= View::escape($errors['institutional_email']) ?></div><?php endif;?></div>
    <div class="col-md-6"><label class="form-label" for="affiliation">Affiliation</label><input class="form-control<?= isset($errors['affiliation'])?' is-invalid':'' ?>" id="affiliation" name="affiliation" maxlength="255" value="<?= View::escape($values['affiliation']??'') ?>"><?php if(isset($errors['affiliation'])):?><div class="invalid-feedback"><?= View::escape($errors['affiliation']) ?></div><?php endif;?></div>
    <div class="col-md-6"><label class="form-label" for="position_type">Position type</label><select class="form-select<?= isset($errors['position_type'])?' is-invalid':'' ?>" id="position_type" name="position_type"><?php foreach($positionLabels as $value=>$label):?><option value="<?= View::escape($value) ?>" <?= ($values['position_type']??'')===$value?'selected':'' ?>><?= View::escape($label) ?></option><?php endforeach;?></select><?php if(isset($errors['position_type'])):?><div class="invalid-feedback"><?= View::escape($errors['position_type']) ?></div><?php endif;?></div>
    <div class="col-md-3"><label class="form-label" for="is_internal">Relationship</label><select class="form-select<?= isset($errors['is_internal'])?' is-invalid':'' ?>" id="is_internal" name="is_internal"><option value="1" <?= ($values['is_internal']??'')==='1'?'selected':'' ?>>Internal</option><option value="0" <?= ($values['is_internal']??'')==='0'?'selected':'' ?>>External</option></select><?php if(isset($errors['is_internal'])):?><div class="invalid-feedback"><?= View::escape($errors['is_internal']) ?></div><?php endif;?></div>
    <div class="col-md-3"><label class="form-label" for="is_active">Status</label><select class="form-select<?= isset($errors['is_active'])?' is-invalid':'' ?>" id="is_active" name="is_active"><option value="1" <?= ($values['is_active']??'')==='1'?'selected':'' ?>>Active</option><option value="0" <?= ($values['is_active']??'')==='0'?'selected':'' ?>>Inactive</option></select><?php if(isset($errors['is_active'])):?><div class="invalid-feedback"><?= View::escape($errors['is_active']) ?></div><?php endif;?></div>
    <div class="col-md-6"><label class="form-label" for="default_monthly_capacity_hours">Standard Monthly Capacity</label><input class="form-control<?= isset($errors['default_monthly_capacity_hours'])?' is-invalid':'' ?>" id="default_monthly_capacity_hours" name="default_monthly_capacity_hours" inputmode="decimal" value="<?= View::escape($values['default_monthly_capacity_hours']??'125.00') ?>"><?php if(isset($errors['default_monthly_capacity_hours'])):?><div class="invalid-feedback"><?= View::escape($errors['default_monthly_capacity_hours']) ?></div><?php endif;?><div class="form-text">Default hours available for project allocation each month. Individual months may override this value.</div><?php if($isEdit&&($hasCapacityOverrides??false)):?><div class="form-text text-warning">Changing the standard monthly capacity affects only months without a specific override.</div><?php endif;?></div>
    <div class="col-md-6"><label class="form-label" for="active_from">Active from</label><input class="form-control<?= isset($errors['active_from'])?' is-invalid':'' ?>" id="active_from" name="active_from" type="date" value="<?= View::escape($values['active_from']??'') ?>"><?php if(isset($errors['active_from'])):?><div class="invalid-feedback"><?= View::escape($errors['active_from']) ?></div><?php endif;?></div>
    <div class="col-md-6"><label class="form-label" for="active_to">Active to</label><input class="form-control<?= isset($errors['active_to'])?' is-invalid':'' ?>" id="active_to" name="active_to" type="date" value="<?= View::escape($values['active_to']??'') ?>"><?php if(isset($errors['active_to'])):?><div class="invalid-feedback"><?= View::escape($errors['active_to']) ?></div><?php endif;?></div>
    <div class="col-12"><label class="form-label" for="notes">Administrative notes</label><textarea class="form-control<?= isset($errors['notes'])?' is-invalid':'' ?>" id="notes" name="notes" maxlength="2000" rows="5"><?= View::escape($values['notes']??'') ?></textarea><div class="form-text">Visible only to administrators; never shown in the list.</div><?php if(isset($errors['notes'])):?><div class="invalid-feedback"><?= View::escape($errors['notes']) ?></div><?php endif;?></div>
</div>
<?php if($isEdit):?><p class="text-secondary small mt-4 mb-0">Created <?= View::escape($person->createdAt->format('Y-m-d H:i')) ?> · Updated <?= View::escape($person->updatedAt->format('Y-m-d H:i')) ?></p><?php endif;?>
<button class="btn btn-primary mt-4 align-self-start" type="submit"><?= $isEdit?'Save changes':'Create person' ?></button>
</form></div></div>
