<?php
declare(strict_types=1);
use App\Support\View;
$editMode=$editMode??$page->canManage;$canEditHours=$canEditHours??$page->canManage;
$project=$page->project;$base=$editMode?'/projects/'.$project->id.'/effort/edit':'/projects/'.$project->id;
$monthName=static fn(int$m):string=>(new DateTimeImmutable("2026-$m-01"))->format('M');
$capacityBy=[];foreach($page->capacity as$c)$capacityBy[$c['participant']->id]=$c;
$colgroup=static function():void{echo'<colgroup><col class="participant-column">';for($m=1;$m<=12;$m++)echo'<col class="month-column-width" data-month-column="'.$m.'">';echo'<col class="annual-column"></colgroup>';};
?>
<div id="annual-effort-grid" data-project-id="<?= $project->id ?>" data-year="<?= $page->year ?>" data-hours-per-pm="<?= View::escape($project->hoursPerPm) ?>" data-has-error="<?= $error===null?'0':'1' ?>">
<div class="d-flex justify-content-between align-items-start mb-3 project-action-header"><div><p class="text-secondary"><?= View::escape($project->displayTitle()) ?></p><h1><?= $editMode?'Edit person-hours':'Project overview' ?></h1><p>Work Package → every project participant → monthly person-hours</p></div><div class="d-flex flex-wrap gap-2 project-actions"><?php if(!$editMode&&$canEditHours):?><a class="btn btn-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/effort/edit',['year'=>$page->year])) ?>">Edit hours</a><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/configure',['year'=>$page->year])) ?>">Configure project</a><?php elseif($editMode):?><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/'.$project->id,['year'=>$page->year])) ?>">Back to project overview</a><?php endif;?><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/',['year'=>$page->year])) ?>">Back to application overview</a></div></div>
<?php if($error!==null):?><div class="alert alert-danger" role="alert" tabindex="-1" data-grid-error><?= View::escape($error) ?></div><?php endif;?>
<div class="d-flex flex-wrap gap-2 mb-3 align-items-center"><a class="btn btn-outline-secondary" data-grid-navigation href="<?= View::escape($urls->to($base,['year'=>$page->year-1])) ?>">← <?= $page->year-1 ?></a><form class="d-flex gap-2" method="get" data-year-form><label class="visually-hidden" for="year">Year</label><input class="form-control" id="year" name="year" value="<?= $page->year ?>" inputmode="numeric"><button class="btn btn-outline-primary">Go</button></form><a class="btn btn-outline-secondary" data-grid-navigation href="<?= View::escape($urls->to($base,['year'=>$page->year+1])) ?>"><?= $page->year+1 ?> →</a></div>
<?php if($page->unassigned['count']>0):?><div class="alert alert-info"><strong>Legacy unassigned effort is excluded.</strong> <?= $page->unassigned['count'] ?> record<?= $page->unassigned['count']===1?'':'s' ?>. <a class="alert-link" href="<?= View::escape($urls->to('/projects/'.$project->id.'/allocations/unassigned')) ?>">Classify unassigned allocations</a>.</div><?php endif;?>
<?php if($page->divergentCount>0):?><div class="alert alert-warning"><strong>Unified totals are incomplete.</strong> <?= $page->divergentCount ?> legacy inconsistent record<?= $page->divergentCount===1?' is':'s are' ?> excluded. Resolve each through its allocation details; unrelated grid saves preserve these records.</div><?php endif;?>

<?php if($page->sections===[]):?><div class="card card-body text-secondary">No Work Packages overlap this year and no classified historical allocations exist.</div><?php else:?>
<div class="card card-body mb-3 grid-tools"><div class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label" for="wp-jump">Work Package</label><select class="form-select" id="wp-jump" data-wp-jump><option value="">Jump to…</option><?php foreach($page->sections as$s):$wp=$s['workPackage'];?><option value="wp-<?= $wp->id ?>"><?= View::escape($wp->displayTitle()) ?></option><?php endforeach;?></select></div><button class="btn btn-outline-secondary" type="button" data-expand-all>Expand all</button><button class="btn btn-outline-secondary" type="button" data-collapse-all>Collapse all</button><div class="mobile-month-tools ms-md-auto"><label class="form-label" for="month-focus">Visible month</label><div class="input-group"><button class="btn btn-outline-secondary" type="button" data-month-previous aria-label="Previous month">←</button><select class="form-select" id="month-focus" data-month-focus><?php for($m=1;$m<=12;$m++):?><option value="<?= $m ?>"><?= (new DateTimeImmutable("2026-$m-01"))->format('F') ?></option><?php endfor;?></select><button class="btn btn-outline-secondary" type="button" data-month-next aria-label="Next month">→</button></div></div></div>
<div class="row g-2 mt-2" data-grid-filters><div class="col-md-3"><label class="form-label" for="participant-filter">Participant</label><input class="form-control" id="participant-filter" data-filter-participant placeholder="Name"></div><div class="col-md-2"><label class="form-label" for="role-filter">Role</label><select class="form-select" id="role-filter" data-filter-role><option value="">All roles</option><?php $roles=[];foreach($page->sections as$s)foreach($s['participants']as$r)$roles[$r['participant']->projectRole]=$r['participant']->roleLabel();ksort($roles);foreach($roles as$v=>$l):?><option value="<?= View::escape($v) ?>"><?= View::escape($l) ?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label" for="wp-filter">WP search</label><input class="form-control" id="wp-filter" data-filter-wp placeholder="Code or title"></div><div class="col-md-2"><label class="form-label" for="wp-active-filter">WP status</label><select class="form-select" id="wp-active-filter" data-filter-wp-active><option value="">All</option><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="col-md-2"><label class="form-label" for="effort-filter">Participants</label><select class="form-select" id="effort-filter" data-filter-state><option value="">All</option><option value="effort">With person-hours</option><option value="capacity">Capacity warnings</option><?php if($page->canManage):?><option value="dirty">With unsaved changes</option><?php endif;?></select></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-outline-secondary w-100" type="button" data-reset-filters>Reset</button></div></div>
<p class="small text-secondary mt-3 mb-0">Keyboard: Enter or Shift+Enter moves across editable months. Arrow keys move to adjacent editable cells when the text cursor is at an edge. Tab and Shift+Tab retain their normal behavior.</p></div>

<?php if($page->canManage):?><form method="post" action="<?= View::escape($urls->to($base)) ?>" data-effort-form><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="year" value="<?= $page->year ?>"><input type="hidden" name="concurrency_token" value="<?= View::escape($page->concurrencyToken) ?>"><?php endif;?>
<?php foreach($page->sections as$index=>$section):$wp=$section['workPackage'];?>
<details class="card mb-3 effort-wp" id="wp-<?= $wp->id ?>" data-wp-id="<?= $wp->id ?>" data-wp-active="<?= $wp->isActive?'1':'0' ?>" data-wp-text="<?= View::escape(strtolower($wp->code.' '.$wp->title)) ?>" <?= $index===0||$error!==null?'open':'' ?>><summary class="card-header"><strong><?= View::escape($wp->displayTitle()) ?></strong> · <?= View::escape($wp->responsibleName()) ?> · <?= $wp->isActive?'Active':'Inactive' ?> · <?= View::escape($wp->period()) ?> · <span data-wp-annual="<?= $wp->id ?>"><?= View::escape($section['annualHours']) ?></span> person-hours <span class="badge text-bg-warning d-none" data-wp-dirty>Unsaved</span><?php if($section['divergentCount']>0):?> <span class="badge text-bg-warning"><?= $section['divergentCount'] ?> divergent</span><?php endif;?><?php if($section['warnings']!==[]):?> <span class="badge text-bg-warning">Warnings</span><?php endif;?></summary>
<div class="card-body p-0"><?php foreach($section['warnings']as$warning):?><div class="alert alert-warning m-2"><?= View::escape($warning) ?></div><?php endforeach;?><div class="table-responsive effort-grid" data-grid-scroll><table class="table table-sm table-bordered align-middle mb-0 effort-table"><?php $colgroup();?><thead><tr><th class="sticky-label">Participant</th><?php for($m=1;$m<=12;$m++):$current=$page->currentMonth===$m;?><th class="month-column<?= $current?' current-month':'' ?>" data-month-column="<?= $m ?>" scope="col" <?= $current?'aria-label="'.View::escape($monthName($m).', current month').'"':'' ?>><div class="month-cell-content"><span><?= $monthName($m) ?></span><?php if($current):?><small class="current-month-label">Current</small><?php endif;?></div></th><?php endfor;?><th><div class="annual-cell-content">Annual</div></th></tr></thead><tbody>
<?php foreach($section['participants']as$row):$participant=$row['participant'];$capacity=$capacityBy[$participant->id]??null;$hasCapacityWarning=$capacity!==null&&(($capacity['monthsOver']??0)>0||($capacity['divergentCount']??0)>0);$hasEffort=$row['annualHours']!=='0.00'||$row['divergentCount']>0;?>
<tr data-participant-row data-participant-id="<?= $participant->id ?>" data-participant-name="<?= View::escape(strtolower($participant->personName())) ?>" data-participant-role="<?= View::escape($participant->projectRole) ?>" data-has-effort="<?= $hasEffort?'1':'0' ?>" data-capacity-warning="<?= $hasCapacityWarning?'1':'0' ?>"><th class="sticky-label" scope="row"><div class="participant-cell-content"><a href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/'.$participant->id.'/allocations',['year'=>$page->year,'work_package_id'=>$wp->id,'context'=>'project-overview'])) ?>"><?= View::escape($participant->personName()) ?></a><?php if($participant->id===$wp->responsibleParticipantId):?> <span class="badge text-bg-info">Responsible</span><?php endif;?><?php if($hasCapacityWarning):?> <a class="badge text-bg-warning" href="#capacity-<?= $participant->id ?>">Capacity warning</a><?php endif;?><small class="d-block text-secondary"><?= View::escape($participant->roleLabel()) ?><?= !$participant->isActive?' · inactive':'' ?></small></div></th>
<?php for($m=1;$m<=12;$m++):$cell=$row['months'][$m];$allocation=$cell['allocation'];$stored=$cell['value'];$submittedValue=$submitted[$wp->id][$participant->id][$m]??null;$value=$submittedValue!==null?(string)$submittedValue:($stored??'');$current=$page->currentMonth===$m;$state=$cell['divergent']?'divergent':(!$cell['allowed']?($allocation===null?'unavailable':'inconsistent'):($stored===null?'null':($stored==='0.00'?'zero':'value')));$description='cell-help-'.$wp->id.'-'.$participant->id.'-'.$m;?>
<td class="effort-cell-state state-<?= $state ?><?= !$page->canManage&&$cell['allowed']?' authorization-readonly':'' ?><?= $current?' current-month':'' ?> month-column" data-month-column="<?= $m ?>" data-cell-state="<?= $state ?>"><div class="month-cell-content">
<?php if($cell['divergent']):?><a class="divergent-value" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/'.$participant->id.'/allocations/'.$allocation->id,['year'=>$page->year,'context'=>'project-overview'])) ?>" aria-describedby="<?= $description ?>">Different values</a><small class="visually-hidden" id="<?= $description ?>">Legacy inconsistent allocation. Resolve in allocation details. Excluded from unified totals.</small>
<?php elseif($page->canManage&&$cell['allowed']):?><label class="visually-hidden" for="c-<?= $wp->id ?>-<?= $participant->id ?>-<?= $m ?>">Person-hours, <?= View::escape($wp->displayTitle().', '.$participant->personName().', '.$monthName($m).' '.$page->year) ?></label><input class="form-control form-control-sm effort-cell" id="c-<?= $wp->id ?>-<?= $participant->id ?>-<?= $m ?>" name="allocations[<?= $wp->id ?>][<?= $participant->id ?>][<?= $m ?>]" value="<?= View::escape($value) ?>" data-initial="<?= View::escape($stored??'') ?>" data-wp="<?= $wp->id ?>" data-participant="<?= $participant->id ?>" data-month="<?= $m ?>" inputmode="decimal" aria-describedby="<?= $description ?>"><small class="visually-hidden" id="<?= $description ?>" data-cell-description><?= $state==='null'?'Empty editable value':($state==='zero'?'Explicit zero':'Stored non-zero value') ?></small>
<?php elseif($allocation!==null):?><a class="<?= !$cell['allowed']?'text-danger':'' ?>" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/'.$participant->id.'/allocations/'.$allocation->id,['year'=>$page->year,'context'=>'project-overview'])) ?>"><?= View::escape($stored??'—') ?></a><span class="visually-hidden"><?= !$cell['allowed']?'Historical value outside current date rules':'Read-only value' ?></span><?php else:?><span aria-label="<?= !$cell['allowed']?'Unavailable due to date rules':'No value, read only' ?>"><?= !$cell['allowed']?'×':'—' ?></span><?php endif;?></div></td><?php endfor;?>
<td><div class="annual-cell-content"><strong data-participant-annual="<?= $wp->id ?>-<?= $participant->id ?>"><?= View::escape($row['annualHours']) ?></strong> h <span class="visually-hidden" data-provisional-label></span><?php if($row['divergentCount']>0):?><small class="d-block text-warning"><?= $row['divergentCount'] ?> excluded</small><?php endif;?></div></td></tr><?php endforeach;?>
<tr class="table-light wp-total-row"><th class="sticky-label" scope="row"><div class="participant-cell-content"><?= View::escape($wp->code) ?> total</div></th><?php for($m=1;$m<=12;$m++):$current=$page->currentMonth===$m;?><td class="month-column<?= $current?' current-month':'' ?>" data-month-column="<?= $m ?>"><div class="month-cell-content"><span data-wp-month="<?= $wp->id ?>-<?= $m ?>"><?= View::escape($section['monthlyHours'][$m]) ?></span></div></td><?php endfor;?><td><div class="annual-cell-content"><strong data-wp-annual-total="<?= $wp->id ?>"><?= View::escape($section['annualHours']) ?></strong> h</div></td></tr></tbody></table></div></div></details><?php endforeach;?>
<div class="table-responsive mb-3 project-total-table"><table class="table table-bordered effort-table"><?php $colgroup();?><tbody><tr class="table-primary"><th class="sticky-label"><div class="participant-cell-content">Unified classified project total</div></th><?php for($m=1;$m<=12;$m++):$current=$page->currentMonth===$m;?><td class="month-column<?= $current?' current-month':'' ?>" data-month-column="<?= $m ?>"><div class="month-cell-content"><span data-project-month="<?= $m ?>"><?= View::escape($page->projectMonthlyHours[$m]) ?></span></div></td><?php endfor;?><td><div class="annual-cell-content"><strong data-project-annual><?= View::escape($page->projectAnnualHours) ?></strong> h <small class="d-block" data-project-pm><?= View::escape($converter->convert($page->projectAnnualHours,$project->hoursPerPm)) ?> PM</small></div></td></tr></tbody></table></div>
<?php if($page->canManage):?><div class="sticky-save-bar card card-body mb-4" data-save-bar><div class="d-flex flex-wrap gap-3 align-items-center"><strong>Person-hours</strong><span aria-live="polite"><span data-dirty-count>0</span> changed cells</span><span class="text-warning d-none" data-provisional-notice>Totals shown are provisional.</span><button class="btn btn-primary ms-md-auto" type="submit" data-save-button>Save person-hours</button><button class="btn btn-outline-secondary" type="button" data-reset-changes>Reset unsaved changes</button></div></div></form><?php endif;?><?php endif;?>

<section class="mt-4" id="capacity-summary"><h2 class="h4">Capacity</h2><p class="text-secondary">Usage is calculated across all projects from unified allocation values for <?= $page->year ?>.</p>
<?php $capacityWarnings=array_values(array_filter($page->capacity,static fn(array$c):bool=>$c['periods']!==[]||$c['divergentCount']>0));?>
<?php if($capacityWarnings===[]):?><div class="alert alert-success">No participant exceeds capacity in the selected year.</div><?php else:?><div class="vstack gap-2"><?php foreach($capacityWarnings as$c):?><article class="card card-body" id="capacity-<?= $c['participant']->id ?>"><strong><?= View::escape($c['participant']->personName()) ?></strong>
<?php if($c['periods']!==[]):?><span class="text-warning-emphasis">Capacity exceeded</span><ul class="mb-0"><?php foreach($c['periods']as$period):?><li><?= (new DateTimeImmutable(sprintf('%04d-%02d-01',$period['year'],$period['month'])))->format('F Y') ?>: <?= View::escape($period['allocatedHours']) ?> / <?= View::escape($period['capacityHours']) ?> h (+<?= View::escape($period['excessHours']) ?> h)</li><?php endforeach;?></ul><?php endif;?>
<?php if($c['divergentCount']>0):?><small class="text-warning-emphasis"><?= $c['divergentCount'] ?> divergent allocation record<?= $c['divergentCount']===1?'':'s' ?> excluded.</small><?php endif;?></article><?php endforeach;?></div><?php endif;?></section>
</div>
