<?php
declare(strict_types=1);
use App\Support\View;
$steps=['details'=>'Project details','work-packages'=>'Work Packages','participants'=>'Participants','review'=>'Review'];
$details=$override?:($state['details']??['acronym'=>'','title'=>'','description'=>'','manager_person_id'=>'','start_date'=>'','end_date'=>'','status'=>'planned','hours_per_pm'=>'125.00','notes'=>'']);
?>
<header class="page-heading"><div><p class="eyebrow">New project</p><h1><?= View::escape($steps[$step]) ?></h1><p class="text-secondary">Structure first; person-hours are entered only after creation.</p></div></header>
<ol class="workflow-steps" aria-label="Project creation progress"><?php $n=0;foreach($steps as$key=>$label):$n++;?><li class="<?= $key===$step?'current':'' ?>" <?= $key===$step?'aria-current="step"':'' ?>><span><?= $n ?></span><?= View::escape($label) ?></li><?php endforeach;?></ol>
<?php if($errors!==[]):?><div class="alert alert-danger" role="alert"><strong>Review this step.</strong><ul class="mb-0"><?php foreach($errors as$error):?><li><?= View::escape($error) ?></li><?php endforeach;?></ul></div><?php endif;?>
<?php if($step==='details'):?>
<form method="post" action="<?= View::escape($urls->to('/projects/create')) ?>" class="card card-body workflow-form"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="step" value="details">
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="acronym">Project code</label><input required maxlength="50" class="form-control" id="acronym" name="acronym" value="<?= View::escape($details['acronym']??'') ?>"></div><div class="col-md-9"><label class="form-label" for="title">Title</label><input required maxlength="255" class="form-control" id="title" name="title" value="<?= View::escape($details['title']??'') ?>"></div>
<div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description"><?= View::escape($details['description']??'') ?></textarea></div>
<div class="col-md-4"><label class="form-label" for="manager_person_id">Manager</label><select class="form-select" id="manager_person_id" name="manager_person_id"><option value="">No manager</option><?php foreach($managerOptions as$manager):?><option value="<?= $manager->id ?>" <?= (string)$manager->id===(string)($details['manager_person_id']??'')?'selected':'' ?>><?= View::escape($manager->name) ?></option><?php endforeach;?></select></div>
<div class="col-md-2"><label class="form-label" for="start_date">Start</label><input class="form-control" type="date" id="start_date" name="start_date" value="<?= View::escape($details['start_date']??'') ?>"></div><div class="col-md-2"><label class="form-label" for="end_date">End</label><input class="form-control" type="date" id="end_date" name="end_date" value="<?= View::escape($details['end_date']??'') ?>"></div>
<div class="col-md-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><?php foreach($statuses as$value=>$label):?><option value="<?= View::escape($value) ?>" <?= $value===($details['status']??'planned')?'selected':'' ?>><?= View::escape($label) ?></option><?php endforeach;?></select></div>
<div class="col-md-2"><label class="form-label" for="hours_per_pm">Hours per PM</label><input required class="form-control" id="hours_per_pm" name="hours_per_pm" value="<?= View::escape($details['hours_per_pm']??'125.00') ?>"></div>
<div class="col-12"><label class="form-label" for="notes">Notes</label><textarea class="form-control" id="notes" name="notes"><?= View::escape($details['notes']??'') ?></textarea></div></div>
<div class="workflow-actions"><button class="btn btn-primary">Continue to Work Packages</button><button class="btn btn-link" name="step" value="cancel" formnovalidate>Cancel</button></div></form>
<?php elseif($step==='work-packages'):?>
<?php $rows=$override['work_packages']??$state['work_packages']??[];while(count($rows)<5)$rows[]=['code'=>'','title'=>'','start_date'=>$state['details']['start_date'],'end_date'=>$state['details']['end_date']];?>
<form method="post" action="<?= View::escape($urls->to('/projects/create')) ?>" class="card card-body workflow-form"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="step" value="work-packages"><p>Leave every row blank to create a project without Work Packages. Person-hours require at least one real WP.</p>
<div class="table-responsive"><table class="table"><thead><tr><th>Code</th><th>Title</th><th>Start</th><th>End</th></tr></thead><tbody><?php foreach($rows as$i=>$row):?><tr><td><input class="form-control" name="work_packages[<?= $i ?>][code]" value="<?= View::escape($row['code']) ?>"></td><td><input class="form-control" name="work_packages[<?= $i ?>][title]" value="<?= View::escape($row['title']) ?>"></td><td><input class="form-control" type="date" name="work_packages[<?= $i ?>][start_date]" value="<?= View::escape($row['start_date']) ?>"></td><td><input class="form-control" type="date" name="work_packages[<?= $i ?>][end_date]" value="<?= View::escape($row['end_date']) ?>"></td></tr><?php endforeach;?></tbody></table></div>
<div class="workflow-actions"><button class="btn btn-primary">Continue to participants</button><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/create')) ?>">Back to details</a></div></form>
<?php elseif($step==='participants'):?>
<?php $selected=[];foreach(($override['participants']??$state['participants']??[])as$row)$selected[(int)$row['person_id']]=$row;?>
<form method="post" action="<?= View::escape($urls->to('/projects/create')) ?>" class="card card-body workflow-form"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="step" value="participants"><p>Select existing registry people. Participation dates default to the project interval and remain editable.</p>
<div class="table-responsive"><table class="table"><thead><tr><th>Select</th><th>Person</th><th>Role</th><th>Start</th><th>End</th></tr></thead><tbody><?php foreach($people as$i=>$person):$row=$selected[$person->id]??null;$lower=array_filter([$state['details']['start_date'],$person->activeFrom?->format('Y-m-d')]);$upper=array_filter([$state['details']['end_date'],$person->activeTo?->format('Y-m-d')]);$defaultStart=$lower===[]?'':max($lower);$defaultEnd=$upper===[]?'':min($upper);?><tr><td><input class="form-check-input" type="checkbox" name="participants[<?= $i ?>][person_id]" value="<?= $person->id ?>" <?= $row!==null?'checked':'' ?> aria-label="Select <?= View::escape($person->fullName()) ?>"></td><td><?= View::escape($person->fullName()) ?></td><td><select class="form-select" name="participants[<?= $i ?>][project_role]"><?php foreach($roles as$value=>$label):?><option value="<?= View::escape($value) ?>" <?= $value===($row['project_role']??'researcher')?'selected':'' ?>><?= View::escape($label) ?></option><?php endforeach;?></select></td><td><input class="form-control" type="date" name="participants[<?= $i ?>][participation_start]" value="<?= View::escape($row['participation_start']??$defaultStart) ?>"></td><td><input class="form-control" type="date" name="participants[<?= $i ?>][participation_end]" value="<?= View::escape($row['participation_end']??$defaultEnd) ?>"></td></tr><?php endforeach;?></tbody></table></div>
<div class="workflow-actions"><button class="btn btn-primary">Review project</button><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/create',['step'=>'work-packages'])) ?>">Back to Work Packages</a></div></form>
<?php else:$details=$state['details'];?>
<div class="card card-body workflow-review"><h2 class="h4"><?= View::escape($details['acronym'].' — '.$details['title']) ?></h2><dl><dt>Manager</dt><dd><?= View::escape($details['manager_person_id']?:'Not assigned') ?></dd><dt>Period</dt><dd><?= View::escape(($details['start_date']?:'Open').' — '.($details['end_date']?:'Open')) ?></dd><dt>Hours per PM</dt><dd><?= View::escape($details['hours_per_pm']) ?></dd></dl>
<h3 class="h5">Work Packages</h3><?php if($state['work_packages']===[]):?><div class="alert alert-warning">No Work Package will be created. Add one before entering person-hours.</div><?php else:?><ul><?php foreach($state['work_packages']as$wp):?><li><?= View::escape($wp['code'].' — '.$wp['title']) ?> (<?= View::escape(($wp['start_date']?:'Open').' — '.($wp['end_date']?:'Open')) ?>)</li><?php endforeach;?></ul><?php endif;?>
<h3 class="h5">Participants</h3><?php if($state['participants']===[]):?><p class="text-secondary">No participants selected.</p><?php else:?><ul><?php foreach($state['participants']as$participant):?><li><?= View::escape($participant['person_name']) ?> — <?= View::escape($roles[$participant['project_role']]??$participant['project_role']) ?></li><?php endforeach;?></ul><?php endif;?>
<form method="post" action="<?= View::escape($urls->to('/projects/create')) ?>"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="step" value="create"><div class="workflow-actions"><button class="btn btn-primary">Create project</button><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/create',['step'=>'participants'])) ?>">Back to participants</a><a class="btn btn-link" href="<?= View::escape($urls->to('/projects/create')) ?>">Back to details</a></div></form></div>
<?php endif;?>
