<?php
declare(strict_types=1);
use App\Support\View;
$edit=$mode==='edit';$action=$edit?'/projects/'.$project->id:'/projects';
?>
<div class="row justify-content-center"><div class="col-xl-10"><div class="d-flex justify-content-between mb-4"><h1 class="h2"><?= View::escape($title) ?></h1><a href="<?= View::escape($urls->to('/projects')) ?>">Back to projects</a></div>
<form class="card card-body shadow-sm" method="post" action="<?= View::escape($urls->to($action)) ?>" novalidate><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><div class="row g-3">
<?php foreach(['acronym'=>['Acronym',50],'title'=>['Title',255]] as $f=>[$l,$m]):?><div class="<?= $f==='acronym'?'col-md-4':'col-md-8' ?>"><label class="form-label" for="<?= $f ?>"><?= $l ?></label><input class="form-control<?= isset($errors[$f])?' is-invalid':'' ?>" id="<?= $f ?>" name="<?= $f ?>" maxlength="<?= $m ?>" value="<?= View::escape($values[$f]??'') ?>" required><?php if(isset($errors[$f])):?><div class="invalid-feedback"><?= View::escape($errors[$f]) ?></div><?php endif;?></div><?php endforeach;?>
<div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control<?= isset($errors['description'])?' is-invalid':'' ?>" id="description" name="description" maxlength="5000" rows="4"><?= View::escape($values['description']??'') ?></textarea><?php if(isset($errors['description'])):?><div class="invalid-feedback"><?= View::escape($errors['description']) ?></div><?php endif;?></div>
<?php foreach(['internal_code'=>'Internal code','grant_agreement_number'=>'Grant agreement number','funding_agency'=>'Funding agency','funding_programme'=>'Funding programme','coordinator_organization'=>'Coordinator organization'] as $f=>$l):?><div class="col-md-6"><label class="form-label" for="<?= $f ?>"><?= $l ?></label><input class="form-control<?= isset($errors[$f])?' is-invalid':'' ?>" id="<?= $f ?>" name="<?= $f ?>" maxlength="<?= in_array($f,['internal_code','grant_agreement_number'],true)?100:255 ?>" value="<?= View::escape($values[$f]??'') ?>"><?php if(isset($errors[$f])):?><div class="invalid-feedback"><?= View::escape($errors[$f]) ?></div><?php endif;?></div><?php endforeach;?>
<div class="col-12"><?php if($user->isAdmin()):?><label class="form-label" for="manager_person_id">Responsible person</label><select class="form-select<?= isset($errors['manager_person_id'])?' is-invalid':'' ?>" id="manager_person_id" name="manager_person_id"><option value="">Unassigned</option><?php foreach($managerOptions as $o):?><option value="<?= $o->id ?>" <?= ($values['manager_person_id']??'')===(string)$o->id?'selected':'' ?>><?= View::escape($o->label()) ?></option><?php endforeach;?></select><?php if(isset($errors['manager_person_id'])):?><div class="invalid-feedback"><?= View::escape($errors['manager_person_id']) ?></div><?php endif;?><?php else:?><label class="form-label">Responsible person</label><p class="form-control-plaintext"><?= View::escape($person->fullName()) ?> — You will remain the responsible project manager.</p><?php endif;?></div>
<?php foreach(['start_date'=>'Start date','end_date'=>'End date'] as $f=>$l):?><div class="col-md-3"><label class="form-label" for="<?= $f ?>"><?= $l ?></label><input class="form-control<?= isset($errors[$f])?' is-invalid':'' ?>" id="<?= $f ?>" name="<?= $f ?>" type="date" value="<?= View::escape($values[$f]??'') ?>"><?php if(isset($errors[$f])):?><div class="invalid-feedback"><?= View::escape($errors[$f]) ?></div><?php endif;?></div><?php endforeach;?>
<div class="col-md-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><?php foreach($statusLabels as $v=>$l):?><option value="<?= $v ?>" <?= ($values['status']??'')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label" for="total_budget">Total budget</label><input class="form-control<?= isset($errors['total_budget'])?' is-invalid':'' ?>" id="total_budget" name="total_budget" inputmode="decimal" value="<?= View::escape($values['total_budget']??'') ?>"><?php if(isset($errors['total_budget'])):?><div class="invalid-feedback"><?= View::escape($errors['total_budget']) ?></div><?php endif;?></div>
<div class="col-md-3"><label class="form-label" for="currency">Currency</label><input class="form-control<?= isset($errors['currency'])?' is-invalid':'' ?>" id="currency" name="currency" maxlength="3" value="<?= View::escape($values['currency']??'') ?>"><?php if(isset($errors['currency'])):?><div class="invalid-feedback"><?= View::escape($errors['currency']) ?></div><?php endif;?></div>
<div class="col-md-9"><label class="form-label" for="website_url">Website URL</label><input class="form-control<?= isset($errors['website_url'])?' is-invalid':'' ?>" id="website_url" name="website_url" maxlength="500" value="<?= View::escape($values['website_url']??'') ?>"><?php if(isset($errors['website_url'])):?><div class="invalid-feedback"><?= View::escape($errors['website_url']) ?></div><?php endif;?></div>
<div class="col-12"><label class="form-label" for="notes">Internal notes</label><textarea class="form-control<?= isset($errors['notes'])?' is-invalid':'' ?>" id="notes" name="notes" maxlength="5000" rows="4"><?= View::escape($values['notes']??'') ?></textarea><?php if(isset($errors['notes'])):?><div class="invalid-feedback"><?= View::escape($errors['notes']) ?></div><?php endif;?></div>
</div><button class="btn btn-primary mt-4 align-self-start" type="submit"><?= $edit?'Save changes':'Create project' ?></button></form></div></div>
