<?php
declare(strict_types=1);
use App\Support\View;
$workPackageSummary=$workPackageSummary??[];$workPackageTotal=$workPackageTotal??0;$activeWorkPackageTotal=$activeWorkPackageTotal??0;$unassignedWorkPackageTotal=$unassignedWorkPackageTotal??0;$canManageWorkPackages=$canManageWorkPackages??false;$workPackageEffortTotals=$workPackageEffortTotals??[];
?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->statusLabel()) ?></p><h1><?= View::escape($project->displayTitle()) ?></h1></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/effort')) ?>">Annual effort grid</a><?php if($canEdit):?><a class="btn btn-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/edit')) ?>">Edit</a><?php endif;?></div></div>
<div class="card card-body shadow-sm"><dl class="row mb-0">
<?php foreach([
'Description'=>$project->description,'Internal code'=>$project->internalCode,'Grant agreement'=>$project->grantAgreementNumber,
'Funding agency'=>$project->fundingAgency,'Funding programme'=>$project->fundingProgramme,'Coordinator'=>$project->coordinatorOrganization,
'Responsible person'=>$project->managerName,'Project period'=>$project->period(),'Budget'=>$project->formattedBudget(),
'Hours per Person-Month'=>$project->hoursPerPm.' hours'
] as $label=>$value):?><dt class="col-md-3"><?= View::escape($label) ?></dt><dd class="col-md-9"><?= View::escape($value??'—') ?></dd><?php endforeach;?>
<?php if($project->websiteUrl!==null):?><dt class="col-md-3">Website</dt><dd class="col-md-9"><a href="<?= View::escape($project->websiteUrl) ?>" target="_blank" rel="noopener noreferrer"><?= View::escape($project->websiteUrl) ?></a></dd><?php endif;?>
<?php if($canViewNotes):?><dt class="col-md-3">Internal notes</dt><dd class="col-md-9"><?= nl2br(View::escape($project->notes??'—')) ?></dd><?php endif;?>
<dt class="col-md-3">Created</dt><dd class="col-md-9"><?= View::escape($project->createdAt->format('Y-m-d H:i')) ?></dd><dt class="col-md-3">Updated</dt><dd class="col-md-9"><?= View::escape($project->updatedAt->format('Y-m-d H:i')) ?></dd>
</dl></div>
<?php if($canStatus):?><form class="card card-body mt-4" method="post" action="<?= View::escape($urls->to('/projects/'.$project->id.'/status')) ?>"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><div class="row align-items-end"><div class="col-sm-5"><label class="form-label" for="status">Change status</label><select class="form-select" id="status" name="status"><?php foreach($statusLabels as $v=>$l):?><option value="<?= $v ?>" <?= $project->status===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><div class="col"><button class="btn btn-outline-primary" type="submit">Update status</button></div></div></form><?php endif;?>
<section class="mt-5"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">Participants</h2><p class="text-secondary mb-0"><?= $participantTotal ?> total; <?= $activeParticipantTotal ?> active</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants')) ?>">View all</a><?php if($canManageParticipants):?><a class="btn btn-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/create')) ?>">Add participant</a><?php endif;?></div></div>
<?php if($participantSummary===[]):?><div class="card card-body text-secondary">No participants have been added to this project.</div><?php else:?><div class="table-responsive bg-white border rounded"><table class="table table-striped align-middle mb-0"><thead><tr><th>Person</th><th>Project role</th><th>Affiliation</th><th>Period</th><th>State</th></tr></thead><tbody><?php foreach($participantSummary as $participant):?><tr><td><a href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/'.$participant->id)) ?>"><?= View::escape($participant->personName()) ?></a></td><td><?= View::escape($participant->roleLabel()) ?></td><td><?= View::escape($participant->affiliation??'—') ?></td><td><?= View::escape($participant->period()) ?></td><td><?= View::escape($participant->activeLabel()) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<p class="form-text mt-2">The responsible project manager is shown separately above and is not automatically a participant.</p></section>
<section class="mt-5"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">Work Packages</h2><p class="text-secondary mb-0"><?= $workPackageTotal ?> total; <?= $activeWorkPackageTotal ?> active; <?= $unassignedWorkPackageTotal ?> without a responsible participant</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/work-packages')) ?>">View registry</a><?php if($canManageWorkPackages):?><a class="btn btn-primary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/work-packages/create')) ?>">Create Work Package</a><?php endif;?></div></div>
<?php if($workPackageSummary===[]):?><div class="card card-body text-secondary">No Work Packages have been registered.</div><?php else:?><div class="table-responsive bg-white border rounded"><table class="table table-striped align-middle mb-0"><thead><tr><th>Code</th><th>Title</th><th>Dates</th><th>Responsible participant</th><th>State</th></tr></thead><tbody><?php foreach($workPackageSummary as$wp):?><tr><td><a href="<?= View::escape($urls->to('/projects/'.$project->id.'/work-packages/'.$wp->id)) ?>"><?= View::escape($wp->code) ?></a></td><td><?= View::escape($wp->title) ?></td><td><?= View::escape($wp->period()) ?></td><td><?= View::escape($wp->responsibleName()) ?></td><td><?= $wp->isActive?'Active':'Inactive' ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><p class="form-text">Work Package responsibility is distinct from project ownership.</p>
</section>
<section class="mt-5"><h2 class="h4">Project person-hours summary</h2><p class="text-secondary">Monthly allocations are summed across the project. Person-Month values use <?= View::escape($project->hoursPerPm) ?> hours/PM.</p><?php if(($divergentEffortCount??0)>0):?><div class="alert alert-warning"><?= $divergentEffortCount ?> legacy inconsistent allocation<?= $divergentEffortCount===1?' is':'s are' ?> excluded; review allocation details.</div><?php endif;?><div class="row g-3"><?php foreach(['Person-hours'=>$unifiedEffortTotals->allocatedHours(),'Derived PM'=>$converter->convert($unifiedEffortTotals->allocatedHours(),$project->hoursPerPm),'Allocation rows'=>(string)$unifiedEffortTotals->allocationCount,'Distinct allocation months'=>(string)$unifiedEffortTotals->distinctMonthCount,'Participants with hours'=>(string)$unifiedEffortTotals->participantCount]as$label=>$value):?><div class="col-sm-6 col-lg"><div class="card card-body"><small class="text-secondary"><?= View::escape($label) ?></small><strong><?= View::escape($value) ?></strong></div></div><?php endforeach;?></div><a class="d-inline-block mt-3" href="<?= View::escape($urls->to('/projects/'.$project->id.'/effort')) ?>">Open annual person-hours grid</a></section>
<div class="alert <?= $unassignedEffortTotals->allocationCount===0?'alert-success':'alert-warning' ?> mt-3"><strong>Effort classification:</strong> <?php if($unassignedEffortTotals->allocationCount===0):?>Complete<?php else:?><a class="alert-link" href="<?= View::escape($urls->to('/projects/'.$project->id.'/allocations/unassigned')) ?>"><?= $unassignedEffortTotals->allocationCount ?> unassigned record<?= $unassignedEffortTotals->allocationCount===1?'':'s' ?> requiring classification</a><?php endif;?></div>
