<?php declare(strict_types=1);use App\Support\View;$decimals=$decimals??new App\Support\DecimalHours();$capacitySummary=$capacitySummary??new App\Models\MonthlyCapacitySummary((int)($values['year']??date('Y')),(int)($values['month']??date('n')),new App\Models\EffectiveCapacity('125.00','standard','125.00',null),'0.00','0.00');$edit=$mode==='edit';$base='/projects/'.$project->id.'/participants/'.$participant->id.'/allocations';$action=$edit?$base.'/'.$allocation->id:$base;$navigation=$navigation??['backPath'=>$base,'backQuery'=>[],'backLabel'=>'Back to All Allocations','contextQuery'=>[]];?>
<div class="row justify-content-center"><div class="col-xl-9"><div class="d-flex justify-content-between mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->displayTitle()) ?> — <?= View::escape($participant->personName()) ?></p><h1 class="h2"><?= View::escape($title) ?></h1></div><a href="<?= View::escape($urls->to($navigation['backPath'],$navigation['backQuery'])) ?>"><?= View::escape($navigation['backLabel']) ?></a></div>
<?php if($project->status!=='active'||!$participant->isActive||!$participant->personIsActive||$participant->linkedUserIsActive===false):?><div class="alert alert-warning">One or more project, participation, person, or linked-account states are inactive. States do not prevent an allocation when date boundaries overlap.</div><?php endif;?>
<div class="card card-body mb-3"><strong>Context</strong><span>Project period: <?= View::escape($project->period()) ?></span><span>Participation: <?= View::escape($participant->period()) ?></span><span>Person association: <?= View::escape(($participant->personActiveFrom?->format('Y-m-d')??'Open').' — '.($participant->personActiveTo?->format('Y-m-d')??'Open')) ?></span><span><?= View::escape($project->hoursPerPm) ?> hours = 1.000 PM. Person-Month values are derived using this project’s current conversion factor.</span></div>
<div class="card card-body mb-3"><strong>Cross-project capacity context for the selected month</strong><span>Effective capacity: <?= View::escape($capacitySummary->capacity->effectiveHours) ?> hours (<?= View::escape($capacitySummary->capacity->source) ?>)</span><span>Already allocated excluding this record: <?= View::escape($capacitySummary->allocatedHours()) ?> hours</span><span>Remaining: <?= View::escape($capacitySummary->remaining($decimals)) ?> hours</span><small class="text-secondary">Capacity warnings are non-blocking and reflect all projects.</small></div>
<form class="card card-body" method="post" action="<?= View::escape($urls->to($action,$navigation['contextQuery'])) ?>" novalidate><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><div class="row g-3">
<div class="col-12"><label class="form-label" for="work_package_id">Work Package <span class="text-danger">*</span></label><select class="form-select<?= isset($errors['work_package_id'])?' is-invalid':'' ?>" id="work_package_id" name="work_package_id" required><option value="">Select a Work Package</option><?php foreach($workPackages as$wp):?><option value="<?= $wp->id ?>" <?= ($values['work_package_id']??'')===(string)$wp->id?'selected':'' ?>><?= View::escape($wp->displayTitle().(!$wp->isActive?' [inactive]':'')) ?></option><?php endforeach;?></select><?php if(isset($errors['work_package_id'])):?><div class="invalid-feedback"><?= View::escape($errors['work_package_id']) ?></div><?php endif;?><div class="form-text">Required. Only Work Packages belonging to this project are available. Inactive Work Packages remain selectable for historical effort.</div></div>
<div class="col-md-4"><label class="form-label" for="year">Year</label><input class="form-control<?= isset($errors['year'])?' is-invalid':'' ?>" id="year" name="year" inputmode="numeric" value="<?= View::escape($values['year']??'') ?>"><?php if(isset($errors['year'])):?><div class="invalid-feedback"><?= View::escape($errors['year']) ?></div><?php endif;?></div>
<div class="col-md-4"><label class="form-label" for="month">Month</label><select class="form-select<?= isset($errors['month'])?' is-invalid':'' ?>" id="month" name="month"><?php for($m=1;$m<=12;$m++):?><option value="<?= $m ?>" <?= ($values['month']??'')===(string)$m?'selected':'' ?>><?= (new DateTimeImmutable(sprintf('2026-%02d-01',$m)))->format('F') ?></option><?php endfor;?></select><?php if(isset($errors['month'])):?><div class="invalid-feedback"><?= View::escape($errors['month']) ?></div><?php endif;?></div>
<div class="col-md-6"><label class="form-label" for="allocated_hours">Allocated hours</label><input class="form-control<?= isset($errors['allocated_hours'])?' is-invalid':'' ?>" id="allocated_hours" name="allocated_hours" inputmode="decimal" value="<?= View::escape($values['allocated_hours']??'') ?>"><?php if(isset($errors['allocated_hours'])):?><div class="invalid-feedback"><?= View::escape($errors['allocated_hours']) ?></div><?php endif;?><div class="form-text">Use a decimal point and at most two decimal places. Values above 1 PM are allowed.</div></div>
<div class="col-12"><label class="form-label" for="notes">Internal notes</label><textarea class="form-control<?= isset($errors['notes'])?' is-invalid':'' ?>" id="notes" name="notes" maxlength="2000" rows="4"><?= View::escape($values['notes']??'') ?></textarea><?php if(isset($errors['notes'])):?><div class="invalid-feedback"><?= View::escape($errors['notes']) ?></div><?php endif;?><div class="form-text">Visible only to the administrator and owning project manager.</div></div>
</div><div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-primary" type="submit"><?= $edit?'Save changes':'Create allocation' ?></button><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to($edit?$base.'/'.$allocation->id:$base,$navigation['contextQuery'])) ?>">Cancel</a></div></form></div></div>
