<?php declare(strict_types=1);use App\Support\View;$filters+=['assignment'=>'all','work_package_id'=>''];$workPackages=$workPackages??[];$base='/projects/'.$project->id.'/participants/'.$participant->id.'/allocations';$pagination=$filters+['per_page'=>$page->perPage];?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->displayTitle()) ?></p><h1 class="h2">Person-Hour Allocations</h1><p><?= View::escape($participant->personName()) ?> — <?= View::escape($participant->roleLabel()) ?></p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to('/projects/'.$project->id.'/participants/'.$participant->id)) ?>">Participant</a><?php if($canManage):?><a class="btn btn-primary" href="<?= View::escape($urls->to($base.'/create')) ?>">Add allocation</a><?php endif;?></div></div>
<div class="alert alert-info">Current conversion: <?= View::escape($project->hoursPerPm) ?> hours = 1.000 PM. Work Package and unassigned rows are summed in all totals.</div>
<div class="row g-3 mb-4"><?php foreach(['Planned hours'=>$totals->plannedHours,'Actual hours'=>$totals->actualHours,'Variance'=>$totals->variance($converter),'Allocation rows'=>(string)$totals->allocationCount,'Distinct months'=>(string)$totals->distinctMonthCount]as$l=>$v):?><div class="col-sm-6 col-lg"><div class="card card-body"><small class="text-secondary"><?= View::escape($l) ?></small><strong><?= View::escape($v) ?></strong></div></div><?php endforeach;?></div>
<form class="card card-body mb-4" method="get" action="<?= View::escape($urls->to($base)) ?>"><div class="row g-3 align-items-end">
<div class="col-md-3"><label class="form-label" for="year">Year</label><input class="form-control" id="year" name="year" inputmode="numeric" value="<?= View::escape($filters['year']) ?>"></div>
<div class="col-md-3"><label class="form-label" for="assignment">WP assignment</label><select class="form-select" id="assignment" name="assignment"><?php foreach(['all'=>'All','assigned'=>'Assigned','unassigned'=>'Unassigned']as$v=>$l):?><option value="<?= $v ?>" <?= $filters['assignment']===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label" for="work_package_id">Work Package</label><select class="form-select" id="work_package_id" name="work_package_id"><option value="">All Work Packages</option><?php foreach($workPackages as$wp):?><option value="<?= $wp->id ?>" <?= $filters['work_package_id']===(string)$wp->id?'selected':'' ?>><?= View::escape($wp->displayTitle()) ?></option><?php endforeach;?></select></div>
<?php foreach(['planned'=>'Planned hours','actual'=>'Actual hours']as$key=>$label):?><div class="col-md-3"><label class="form-label" for="<?= $key ?>"><?= $label ?></label><select class="form-select" id="<?= $key ?>" name="<?= $key ?>"><?php foreach(['all'=>'All','present'=>'Present','absent'=>'Absent']as$v=>$l):?><option value="<?= $v ?>" <?= $filters[$key]===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><?php endforeach;?>
<div class="col-md-3"><label class="form-label" for="variance">Variance</label><select class="form-select" id="variance" name="variance"><?php foreach(['all'=>'All','same'=>'Same','different'=>'Different']as$v=>$l):?><option value="<?= $v ?>" <?= $filters['variance']===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><div class="col-12"><button class="btn btn-primary">Apply</button> <a class="btn btn-outline-secondary" href="<?= View::escape($urls->to($base)) ?>">Reset</a></div></div></form>
<div class="table-responsive bg-white border rounded"><table class="table table-striped align-middle mb-0"><thead><tr><th>Month</th><th>Work Package</th><th>Planned h</th><th>Actual h</th><th>Variance</th><th>Planned PM</th><th>Actual PM</th><th>Warnings</th><th>Actions</th></tr></thead><tbody>
<?php foreach($page->items as$a):?><tr><td><a href="<?= View::escape($urls->to($base.'/'.$a->id)) ?>"><?= View::escape($a->monthLabel()) ?></a></td><td><?= View::escape($a->workPackageLabel()) ?></td><td><?= View::escape($a->plannedHours??'—') ?></td><td><?= View::escape($a->actualHours??'—') ?></td><td><?= View::escape($a->hourVariance($converter)??'—') ?></td><td><?= View::escape($a->plannedPm($converter)??'—') ?></td><td><?= View::escape($a->actualPm($converter)??'—') ?></td><td><?php foreach($a->warnings()as$warning):?><span class="text-warning-emphasis"><?= View::escape($warning) ?></span><?php endforeach;?></td><td><?php if($canManage):?><a class="btn btn-sm btn-outline-primary" href="<?= View::escape($urls->to($base.'/'.$a->id.'/edit')) ?>">Edit</a><?php endif;?></td></tr><?php endforeach;?>
<?php if($page->items===[]):?><tr><td colspan="9" class="text-center text-secondary py-4">No allocations match these criteria.</td></tr><?php endif;?></tbody></table></div>
<?php if($page->pageCount()>1):?><nav class="mt-4"><ul class="pagination"><?php for($n=1;$n<=$page->pageCount();$n++):?><li class="page-item <?= $n===$page->page?'active':'' ?>"><a class="page-link" href="<?= View::escape($urls->to($base,$pagination+['page'=>$n])) ?>"><?= $n ?></a></li><?php endfor;?></ul></nav><?php endif;?>
