<?php declare(strict_types=1);use App\Support\View;$filters+=['assignment'=>'all','work_package_id'=>''];$workPackages=$workPackages??[];$base='/projects/'.$project->id.'/participants/'.$participant->id.'/allocations';$navigation=$navigation??['backPath'=>'/projects/'.$project->id.'/participants','backQuery'=>[],'backLabel'=>'Back to Participants','contextQuery'=>[]];$pagination=$filters+$navigation['contextQuery']+['per_page'=>$page->perPage];?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-secondary mb-1"><?= View::escape($project->displayTitle()) ?></p><h1 class="h2">Person-Month Allocation — <?= View::escape($participant->personName()) ?></h1><p><?= View::escape($participant->roleLabel()) ?></p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?= View::escape($urls->to($navigation['backPath'],$navigation['backQuery'])) ?>"><?= View::escape($navigation['backLabel']) ?></a><?php if($canManage):?><a class="btn btn-primary" href="<?= View::escape($urls->to($base.'/create',$navigation['contextQuery'])) ?>">Add allocation</a><?php endif;?></div></div>
<div class="alert alert-info">Current conversion: <?= View::escape($project->hoursPerPm) ?> hours = 1.000 PM. Work Package and unassigned rows are summed in all totals.</div>
<div class="row g-3 mb-4"><?php foreach(['Allocated hours'=>$totals->allocatedHours(),'Allocation rows'=>(string)$totals->allocationCount,'Distinct months'=>(string)$totals->distinctMonthCount]as$l=>$v):?><div class="col-sm-6 col-lg"><div class="card card-body"><small class="text-secondary"><?= View::escape($l) ?></small><strong><?= View::escape($v) ?></strong></div></div><?php endforeach;?></div>
<form class="filter-toolbar mb-4" method="get" action="<?= View::escape($urls->to($base)) ?>"><?php foreach($navigation['contextQuery']as$key=>$value):?><input type="hidden" name="<?= View::escape($key) ?>" value="<?= View::escape((string)$value) ?>"><?php endforeach;?><div class="row g-3 align-items-end">
<div class="col-md-3"><label class="form-label" for="year">Year</label><input class="form-control" id="year" name="year" inputmode="numeric" value="<?= View::escape($filters['year']) ?>"></div>
<div class="col-md-3"><label class="form-label" for="assignment">WP assignment</label><select class="form-select" id="assignment" name="assignment"><?php foreach(['all'=>'All','assigned'=>'Assigned','unassigned'=>'Unassigned']as$v=>$l):?><option value="<?= $v ?>" <?= $filters['assignment']===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label" for="work_package_id">Work Package</label><select class="form-select" id="work_package_id" name="work_package_id"><option value="">All Work Packages</option><?php foreach($workPackages as$wp):?><option value="<?= $wp->id ?>" <?= $filters['work_package_id']===(string)$wp->id?'selected':'' ?>><?= View::escape($wp->displayTitle()) ?></option><?php endforeach;?></select></div>
<div class="col-12"><button class="btn btn-primary">Apply</button> <a class="btn btn-outline-secondary" href="<?= View::escape($urls->to($base,$navigation['contextQuery'])) ?>">Reset</a></div></div></form>
<div class="table-responsive bg-white border rounded"><table class="table table-striped align-middle mb-0"><thead><tr><th>Month</th><th>Work Package</th><th>Allocated h</th><th>Allocated PM</th><th>Warnings</th><th>Actions</th></tr></thead><tbody>
<?php foreach($page->items as$a):?><tr><td><a href="<?= View::escape($urls->to($base.'/'.$a->id,$navigation['contextQuery'])) ?>"><?= View::escape($a->monthLabel()) ?></a></td><td><?= View::escape($a->workPackageLabel()) ?></td><td><?= View::escape($a->allocatedHours()??'—') ?></td><td><?= View::escape($a->allocatedPm($converter)??'—') ?></td><td><?php foreach($a->warnings()as$warning):?><span class="text-warning-emphasis"><?= View::escape($warning) ?></span><?php endforeach;?></td><td><?php if($canManage):?><a class="btn btn-sm btn-outline-primary" href="<?= View::escape($urls->to($base.'/'.$a->id.'/edit',$navigation['contextQuery'])) ?>">Edit</a><?php endif;?></td></tr><?php endforeach;?>
<?php if($page->items===[]):?><tr><td colspan="6" class="text-center text-secondary py-4">No allocations match these criteria.</td></tr><?php endif;?></tbody></table></div>
<?php if($page->pageCount()>1):?><nav class="mt-4"><ul class="pagination"><?php for($n=1;$n<=$page->pageCount();$n++):?><li class="page-item <?= $n===$page->page?'active':'' ?>"><a class="page-link" href="<?= View::escape($urls->to($base,$pagination+['page'=>$n])) ?>"><?= $n ?></a></li><?php endfor;?></ul></nav><?php endif;?>
