<?php declare(strict_types=1);use App\Support\View;$action='/projects/'.$project->id.'/participants/'.$participant->id.'/allocations/'.$allocation->id;?>
<div class="row justify-content-center"><div class="col-lg-8">
<p class="text-secondary"><?= View::escape($project->displayTitle()) ?> — <?= View::escape($participant->personName()) ?></p>
<h1 class="h2">Classify legacy unassigned allocation</h1>
<div class="alert alert-warning"><strong>Legacy unassigned effort.</strong> A real Work Package is now required. Reclassification preserves this record’s period, hours, notes, and ID.</div>
<div class="card card-body mb-3"><dl class="row mb-0"><?php foreach(['Participant'=>$participant->personName(),'Month'=>$allocation->monthLabel(),'Planned hours'=>$allocation->plannedHours??'—','Actual hours'=>$allocation->actualHours??'—','Existing notes'=>$allocation->notes??'—']as$l=>$v):?><dt class="col-sm-4"><?= View::escape($l) ?></dt><dd class="col-sm-8"><?= nl2br(View::escape($v)) ?></dd><?php endforeach;?></dl></div>
<?php if($workPackages===[]):?><div class="alert alert-danger">Create at least one Work Package before classifying project effort. <a class="alert-link" href="<?= View::escape($urls->to('/projects/'.$project->id.'/work-packages')) ?>">Open Work Package registry</a>.</div>
<?php else:?><form class="card card-body" method="post" action="<?= View::escape($urls->to($action)) ?>"><input type="hidden" name="_csrf" value="<?= View::escape($csrfToken) ?>"><label class="form-label" for="work_package_id">Work Package <span class="text-danger">*</span></label><select class="form-select<?= isset($errors['work_package_id'])?' is-invalid':'' ?>" id="work_package_id" name="work_package_id" required><option value="">Select a Work Package</option><?php foreach($workPackages as$wp):?><option value="<?= $wp->id ?>" <?= ($values['work_package_id']??'')===(string)$wp->id?'selected':'' ?>><?= View::escape($wp->displayTitle().(!$wp->isActive?' [inactive]':'')) ?></option><?php endforeach;?></select><?php if(isset($errors['work_package_id'])):?><div class="invalid-feedback"><?= View::escape($errors['work_package_id']) ?></div><?php endif;?><button class="btn btn-primary mt-3 align-self-start">Classify allocation</button></form><?php endif;?>
<a class="d-inline-block mt-3" href="<?= View::escape($urls->to('/projects/'.$project->id.'/allocations/unassigned')) ?>">Back to unassigned allocations</a>
</div></div>
